baseURL: "https://xrpk.github.io" 
title: Ryan Krell
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 1
        - name: About
          url: about/
          weight: 2
        - name: Resume
          url: RyanKrell.pdf
          weight: 3
        - name: Contact
          url: contact/
          weight: 4

params:
    description: "This website hosts Ryan Krell's portfolio and contact information."
    author: Ryan Krell
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ryan Krell
          subtitle: |
            ğŸ’¡ I'm a Computer Science student at SIUE, minoring in Business. I currently work as an IT Infrastructure Intern at Energizer Holdings.

                I'm passionate about technology, health, and volleyball.

                <hr style="width: 50%; margin: 1.2em auto;">

                **ğŸ”§ Tech Stack**  
                <div style="text-align: center;">
                  ğŸ Python &nbsp; ğŸ§ Linux &nbsp; ğŸ§° Bash &nbsp; ğŸ³ Docker &nbsp; ğŸ’» Git/GitHub &nbsp; ğŸ“¦ APIs <br>
                  ğŸŒ HTML/CSS &nbsp; âš™ï¸ JavaScript &nbsp; ğŸ“Š Pandas Â· NumPy &nbsp; âœï¸ Markdown &nbsp; ğŸ–¥ï¸ VS Code
                </div>

          imageUrl: "pfp.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: About
              url: about/
            - name: Resume
              url: RyanKrell.pdf
            - name: Contact
              url: contact/
    classes: "center-profile-buttons center-social-icons"
    socialIcons:
        - name: CV
          url: RyanKrell.pdf
        - name: Email
          url: ryan.krell@icloud.com
        - name: Zoom
          url: https://www.zoom.us/my/ryank
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/
        - name: GitHub
          url: https://github.com/xrpk

    assets:
        disableScrollBarStyle: true
        customCSS: ["css/custom.css"]
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ryan Krell"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
